---
contentDir: "content"
layoutDir: "layouts"
publishDir: "public"
indexes:
  category: "categories"
baseURL: "http://karissademi.github.io/hugo-test"
title: "My first Hugo site"
canonifyURLs: true
theme: "test-theme"
